name: Bug Report
description: File a bug report - for CAM-SIMA developers' use only (all other users should use the CESM forum)
title: "Put brief (<65 char) bug title here!"
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also - what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What are the steps to reproduce the bug?
      description: How can we see this issue?
      placeholder: ex. Sneeze twice and then do a 5-second jig
    validations:
      required: true
  - type: input
    id: cam-tag
    attributes:
      label: What CAM-SIMA hash were you using?
      description: Type "git rev-parse --short HEAD" to see the hash
      placeholder: ex. abc123
    validations:
      required: true
  - type: dropdown
    id: machine
    attributes:
      label: What machine were you running CAM-SIMA on?
      multiple: true
      options:
        - CISL machine (e.g. cheyenne)
        - CGD machine (e.g. izumi)
        - Docker container
        - Personal Computer
        - Other (please explain below)
    validations:
      required: true
  - type: dropdown
    id: compiler
    attributes:
      label: What compiler were you using?
      multiple: true
      options:
        - Intel
        - GNU
        - NAG
        - NVHPC
        - PGI
        - Other (please specify below)
    validations:
      required: true
  - type: input
    id: case-directory
    attributes:
      label: Path to a case directory, if applicable
      description: The full path to a case in which the error occurred
      placeholder: ex. /glade/scratch/3p0/where-could-he-be
    validations:
      required: false
  - type: dropdown
    id: implemenation
    attributes:
      label: Will you be addressing this bug yourself?
      description: If Yes, please also assign this issue to yourself (if possible)
      multiple: false
      options:
        - "Yes"
        - "Yes, but I will need some help"
        - "No"
        - "Any Software Engineer can do this"
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Extra info
      description: Please provide any additional information here that you think might be relevant
      placeholder: ex. I am running CAM-SIMA on izumi and I don't know what compiler I'm using.
    validations:
      required: false
