blank_issues_enabled: false
contact_links:
  - name: CESM forums
    url: https://bb.cgd.ucar.edu/cesm/forums/cam.133/
    about: For support with model use, troubleshooting, etc., please use the CESM forum
