name: CAM-SIMA Fortran CI

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - staging/**
      - development
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} - ${{ github.ref }}

jobs:
  # This check is the stepped leader to determine if the rest of jobs should run. We unfortunately cannot use path filtering
  # due to the peculiar limitations of GitHub Actions, quoted below for reference:
  #
  # "If a workflow is skipped due to path filtering, then checks associated with that workflow will remain in a "Pending" state.
  # A pull request that requires those checks to be successful will be blocked from merging."
  conditional-check:
    name: Check if jobs should run
    runs-on: ubuntu-slim
    outputs:
      # Encoded in base64 to preserve the matched paths exactly.
      matched-paths: ${{ steps.conditional.outputs.matched-paths }}
      should-run: ${{ steps.conditional.outputs.should-run }}
    timeout-minutes: 1
    steps:
      - name: Checkout CAM-SIMA
        uses: actions/checkout@v7

      - name: Check if there are changes to Fortran source code
        id: conditional
        run: |
          set -euo pipefail

          write_result_and_exit() {
            if [ -f matched-paths.txt ]; then
              echo "matched-paths=$(base64 -w 0 < matched-paths.txt)" >> "$GITHUB_OUTPUT"
            else
              echo "matched-paths=" >> "$GITHUB_OUTPUT"
            fi

            case "$1" in
              false)
                echo "Result: Skip jobs."
                echo "should-run=$1" >> "$GITHUB_OUTPUT"
                exit 0
                ;;
              true)
                echo "Result: Run jobs."
                echo "should-run=$1" >> "$GITHUB_OUTPUT"
                exit 0
                ;;
              error|*)
                echo "Error occurred!"
                exit 1
                ;;
            esac
          }

          case "${{ github.event_name }}" in
            pull_request)
              echo "Event is pull request."

              HEAD_COMMIT="${{ github.sha }}"

              if [ -z "$HEAD_COMMIT" ]; then
                echo "HEAD_COMMIT is empty."
                write_result_and_exit false
              fi

              echo "Fetching $HEAD_COMMIT with parents..."
              git fetch --depth=2 origin "$HEAD_COMMIT" || write_result_and_exit error

              BASE_COMMIT="$(git rev-parse $HEAD_COMMIT^1)" || write_result_and_exit error
              ;;
            push)
              echo "Event is push."

              BASE_COMMIT="${{ github.event.before }}"
              HEAD_COMMIT="${{ github.event.after }}"

              if [ -z "$BASE_COMMIT" ] || [ -z "$HEAD_COMMIT" ]; then
                echo "BASE_COMMIT or HEAD_COMMIT is empty."
                write_result_and_exit false
              fi

              if [ -z "${BASE_COMMIT//0/}" ] || [ -z "${HEAD_COMMIT//0/}" ]; then
                echo "BASE_COMMIT or HEAD_COMMIT is null."
                write_result_and_exit false
              fi

              echo "Fetching $BASE_COMMIT..."
              git fetch --depth=1 origin "$BASE_COMMIT" || write_result_and_exit error

              echo "Fetching $HEAD_COMMIT..."
              git fetch --depth=1 origin "$HEAD_COMMIT" || write_result_and_exit error
              ;;
            workflow_dispatch)
              echo "Event is workflow dispatch."

              # Always run jobs when triggered manually.
              write_result_and_exit true
              ;;
            *)
              echo "Event is unknown."

              # Always skip jobs for any other events.
              write_result_and_exit false
              ;;
          esac

          echo "Finding changed paths between $BASE_COMMIT..$HEAD_COMMIT..."
          git diff --name-only "$BASE_COMMIT..$HEAD_COMMIT" | tee changed-paths.txt || write_result_and_exit error

          if grep -E '^\.github/workflows/cam_sima_fortran_ci\.yml$|^share$|^src/.+$|^test/unit/.+$' changed-paths.txt > matched-paths.txt; then
            write_result_and_exit true
          else
            write_result_and_exit false
          fi
  # This job evaluates the overall status of CAM-SIMA Fortran CI for the purpose of inclusion as a required status check.
  # It exists solely due to, again, the peculiar limitations of GitHub Actions, quoted below for reference:
  #
  # "The `jobs.<job_id>.if` conditional is evaluated before `jobs.<job_id>.strategy.matrix` is applied." This implies that
  # when a matrix job is set as a required status check, skipping it due to the conditional will cause a pull request to be
  # blocked from merging.
  overall-status:
    name: Overall status (CAM-SIMA Fortran CI)
    needs:
      - conditional-check
      - source-code-linting
      - unit-tests
    if: ${{ always() }}
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      - name: Evaluate overall status
        run: |
          set -euo pipefail

          write_result_and_exit() {
            case "$1" in
              false)
                echo "Result: Failure."
                exit 1
                ;;
              true)
                echo "Result: Success."
                exit 0
                ;;
              error|*)
                echo "Error occurred!"
                exit 1
                ;;
            esac
          }

          case "${{ needs.conditional-check.result }}" in
            success)
              :
              ;;
            cancelled|failure|skipped)
              write_result_and_exit false
              ;;
            *)
              write_result_and_exit error
              ;;
          esac

          case "${{ needs.source-code-linting.result }}" in
            skipped|success)
              :
              ;;
            cancelled|failure)
              write_result_and_exit false
              ;;
            *)
              write_result_and_exit error
              ;;
          esac

          case "${{ needs.unit-tests.result }}" in
            skipped|success)
              :
              ;;
            cancelled|failure)
              write_result_and_exit false
              ;;
            *)
              write_result_and_exit error
              ;;
          esac

          write_result_and_exit true
  source-code-linting:
    name: Lint Fortran source code
    needs: conditional-check
    if: ${{ needs.conditional-check.outputs.should-run == 'true' }}
    runs-on: ubuntu-slim
    env:
      FORTITUDE_VERSION: 0.9.*
      SOURCE_CODE_PATH: ${{ github.workspace }}
    timeout-minutes: 10
    steps:
      - name: Checkout CAM-SIMA
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          cache: pip
          python-version: 3.12

      - name: Install Fortitude
        run: |
          python3 -m venv venv-fortitude
          source venv-fortitude/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install "fortitude-lint==$FORTITUDE_VERSION"

      - name: Lint Fortran source code
        run: |
          # Retrieve the matched paths.
          echo "${{ needs.conditional-check.outputs.matched-paths }}" | base64 -d > matched-paths.txt

          # Filter Fortran files for Fortitude.
          # Fortitude will choke if it encounters non-Fortran files in the command line arguments.
          if grep -E '[^/]+\.(F|f|F90|f90|pf)$' matched-paths.txt > filtered-paths.txt; then
            set --
            while IFS="" read -r LINE || [ -n "$LINE" ]; do
              [ -f "$LINE" ] && set -- "$@" "$LINE"
            done < filtered-paths.txt

            # Fortitude will still choke if there are no command line arguments.
            if [ "$#" -gt 0 ]; then
              source venv-fortitude/bin/activate
              # First run: Annotated output for GitHub Actions.
              fortitude \
                --config-file "$SOURCE_CODE_PATH/test/fortitude.toml" \
                check \
                --exit-zero \
                --output-format github \
                "$@" | sed -e "s|file=$SOURCE_CODE_PATH/|file=|g"
              # Second run: Output to a log file for uploading.
              fortitude \
                --config-file "$SOURCE_CODE_PATH/test/fortitude.toml" \
                check \
                --exit-zero \
                --output-file "$SOURCE_CODE_PATH/source-code-linting.log" \
                "$@"
            fi
          fi

      - name: Upload Fortran source code linting log
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: ignore
          name: source-code-linting-log
          path: ${{ env.SOURCE_CODE_PATH }}/source-code-linting.log
          retention-days: 7
  unit-tests:
    name: Build and run unit tests (${{ matrix.compiler }})
    needs: conditional-check
    if: ${{ needs.conditional-check.outputs.should-run == 'true' }}
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/kuanchihwang/atm-sci-container:2026-06-12_${{ matrix.compiler }}_${{ matrix.mpi }}
    env:
      CONTAINER_PRESET: cesm
      CONTAINER_ENVIRONMENT: pfunit
      RRTMGP_DATA_REFERENCE: v1.9
      UNIT_TESTS_BUILD_TYPE: Debug
      UNIT_TESTS_PATH: ${{ github.workspace }}/test/unit/fortran
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gnu-11
          - gnu-12
          - gnu-13
          - gnu-14
          - gnu-15
          - intel-2024
          - intel-2025
        # Uncomment the following lines to test with more MPI implementations. Currently only `open-mpi-5`
        # (Open MPI 5.0.x series) is enabled. We may expand this matrix as our test coverage grows in the future.
        mpi:
          # - mpich-4
          # - open-mpi-4
          - open-mpi-5
        # include:
        #   - compiler: intel-2024
        #     mpi: intel-mpi
        #   - compiler: intel-2025
        #     mpi: intel-mpi
    timeout-minutes: 10
    steps:
      - name: Checkout CAM-SIMA
        uses: actions/checkout@v7

      - name: Checkout dependencies
        run: |
          ./bin/git-fleximod update ncar-physics share

      - name: Checkout rrtmgp-data for PIO file reader tests
        uses: actions/checkout@v7
        with:
          repository: earth-system-radiation/rrtmgp-data
          ref: ${{ env.RRTMGP_DATA_REFERENCE }}
          path: ${{ env.UNIT_TESTS_PATH }}/rrtmgp-data

      - name: Build unit tests
        run: |
          source "$(command -v container-entrypoint-hook.sh)"
          cmake \
            -D CMAKE_BUILD_TYPE="$UNIT_TESTS_BUILD_TYPE" \
            -D CAM_SIMA_ENABLE_CODE_COVERAGE=ON \
            -D CAM_SIMA_ENABLE_IO_TESTS=ON \
            -D CAM_SIMA_ENABLE_TESTS=ON \
            -B "$UNIT_TESTS_PATH/build" \
            -S "$UNIT_TESTS_PATH"
          cmake \
            --build "$UNIT_TESTS_PATH/build" \
            --config "$UNIT_TESTS_BUILD_TYPE"

      - name: Run unit tests
        run: |
          source "$(command -v container-entrypoint-hook.sh)"
          ctest \
            --build-config "$UNIT_TESTS_BUILD_TYPE" \
            --output-junit "$UNIT_TESTS_PATH/build/unit-tests.xml" \
            --output-on-failure \
            --test-dir "$UNIT_TESTS_PATH/build" \
            --test-output-size-failed 524288 \
            --test-output-size-passed 524288 \
            --verbose

      - name: Upload unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: ignore
          name: unit-tests-xml-${{ matrix.compiler }}
          path: ${{ env.UNIT_TESTS_PATH }}/build/unit-tests.xml
          retention-days: 7

      # Code coverage analysis only works reliably with the GNU Compiler Collection.
      # Do it only with the latest version to save CI time.

      - name: Install Gcovr
        if: ${{ matrix.compiler == 'gnu-15' }}
        run: |
          python3 -m venv venv-gcovr
          source venv-gcovr/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install gcovr

      - name: Run Gcovr
        if: ${{ matrix.compiler == 'gnu-15' }}
        run: |
          source venv-gcovr/bin/activate
          export SOURCE_PATH="$PWD"
          cd "$UNIT_TESTS_PATH/build"
          gcovr \
            --filter "$SOURCE_PATH/src" \
            --html code-coverage.html \
            --root "$SOURCE_PATH" \
            --verbose \
            .

      - name: Upload code coverage results
        if: ${{ always() && matrix.compiler == 'gnu-15' }}
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: ignore
          name: code-coverage-html
          path: ${{ env.UNIT_TESTS_PATH }}/build/code-coverage.html
          retention-days: 7
