on:
  pull_request:
jobs:
  fleximod-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # oldest supported and latest supported
        python-version: ["3.8", "3.x"]
    steps:
      - id: checkout-CESM
        uses: actions/checkout@v4
      - id: run-fleximod
        run: |
          $GITHUB_WORKSPACE/bin/git-fleximod update
          $GITHUB_WORKSPACE/bin/git-fleximod test
        
          
