name: Pull Request (PR) open and sync workflow

on:
  pull_request:
   types: [opened, synchronize, reopened]

jobs:
  #This job is designed to run all python unit and doctests whenever
  #a PR is either opened or synced (i.e. additional commits are pushed
  #to branch involved in PR).
  python_unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #All of these python versions will be used to run tests:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    # Acquire github action routines:
    - uses: actions/checkout@v2
    # Acquire specific version of python:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # Install xmllint so tests pass:
    - name: Install xmllint
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils
    # Run "checkout_externals":
    - name: Checkout externals
      run: manage_externals/checkout_externals --externals Externals_CAM.cfg ccpp-framework
    # Run python unit and doctests:
    - name: python unit tests
      run: |
        # CAM config doctests:
        python cime_config/cam_config.py
        # CAM config unit tests:
        python test/unit/cam_config_unit_tests.py
        # Registry generator doctests:
        python -m doctest src/data/generate_registry_data.py
        # Registry generator unit tests:
        python test/unit/test_registry.py
        # Physics variable init (phys_init) generator unit tests:
        python test/unit/write_init_unit_tests.py
