name: Pull Request (PR) open and sync workflow

on:
  pull_request:
   types: [opened, synchronize, reopened]

jobs:
  #This job is designed to run all python unit and doctests whenever
  #a PR is either opened or synced (i.e. additional commits are pushed
  #to branch involved in PR).
  python_unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #All of these python versions will be used to run tests:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
    # Acquire github action routines:
    - uses: actions/checkout@v3
    # Acquire specific version of python:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # Install xmllint so tests pass:
    - name: Install xmllint
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils
    # Install pytest so that certain doctests can be caught correctly:
    - name: install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    # Run "checkout_externals":
    - name: Checkout externals
      run: |
        manage_externals/checkout_externals --externals Externals_CAM.cfg ccpp-framework
        manage_externals/checkout_externals --externals Externals.cfg cime
    # Run python unit and doctests:
    - name: python unit tests
      run: |
        # CAM config doctests:
        python cime_config/cam_config.py
        # CAM config unit tests:
        python test/unit/cam_config_unit_tests.py
        # CAM autogen doctests:
        python cime_config/cam_autogen.py
        # CAM build cache doctests:
        python cime_config/cam_build_cache.py
        # Namelist reader generator doctests:
        python cime_config/create_readnl_files.py
        # Registry generator doctests:
        pytest src/data/generate_registry_data.py --doctest-modules
        # ParamGen atm_in namelist writer doctests:
        pytest cime_config/atm_in_paramgen.py --doctest-modules
        # Registry generator unit tests:
        python test/unit/test_registry.py
        # Namelist reader autogeneration unit tests
        python test/unit/create_readnl_files_tests.py
        # Physics variable init (phys_init) generator unit tests:
        python test/unit/write_init_unit_tests.py
        # ParamGen atm_in namelist writer unit tests:
        python test/unit/test_atm_in_paramgen.py

#####

  #This job is designed to run tests on all source-code files
  #modified by the Pull Request (PR).  This is done by running
  #a master python script which collects all modified files,
  #and then passes those files off to additional scripts
  #to run the actual tests.
  source_code_tests:
    runs-on: ubuntu-latest
    steps:
    # acquire github action routines
    - uses: actions/checkout@v3
    # acquire specific version of python
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10" # Use python 3.8
    # install required python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Install latest version of PIP
        pip install PyGithub                 # Install PyGithub python package
        pip install pylint                   # Install Pylint python package
    # run CAM source code testing master script:
    - name: source-code testing python script
      env:
        PR_NUMBER: ${{ github.event.number }}
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/scripts/pr_mod_file_tests.py --access_token $ACCESS_TOKEN --pr_num $PR_NUMBER --rcfile test/.pylintrc --pylint_level 9.5

